
spring:
  application:
    name: ResourceServer
  config:
    import: optional:file:src/main/resources/env.properties
  datasource:
    url: jdbc:mysql://localhost:3306/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  security:
    oauth2:
      resourceserver:
#        opaquetoken:
#          client-id: ${KEYCLOAK_CLIENT_ID}
#          client-secret: ${KEYCLOAK_CLIENT_SECRET}
#          introspection-uri: http://localhost:9090/realms/Techiebroz/protocol/openid-connect/token/introspect
        jwt:
          issuer-uri: http://localhost:9090/realms/Techiebroz

server:
  port: 8000
springdoc:
  swagger-ui:
    oauth:
      client-id: ${KEYCLOAK_CLIENT_ID}
      client-secret: ${KEYCLOAK_CLIENT_SECRET}


keycloak-config:
  realm: ${KEYCLOAK_REALM}
  server-url: http://127.0.0.1:9090
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-admin-id: ${KEYCLOAK_ADMIN_CLIENT_ID}
  grant-type: password
  name: ${KEYCLOAK_ADMIN_USERNAME}
  password: ${KEYCLOAK_ADMIN_PASSWORD}

logging:
  level:
    org:
      keycloak: DEBUG
      springframework:
        security: DEBUG
